from __future__ import annotations
from models import Digest, AnalyzedItem, Recommendation, CategorySection

REC_LABELS = {
    Recommendation.MUST_READ: "⭐必读",
    Recommendation.RECOMMENDED: "👍推荐",
    Recommendation.MONITOR: "👁️待关注",
    Recommendation.OPTIONAL: "📌可选",
}


def _item_to_feishu_elements(item: AnalyzedItem) -> list[dict]:
    elements = []
    elements.append({
        "tag": "markdown",
        "content": f"**[{item.title}]({item.url})**",
    })
    rec_label = REC_LABELS.get(item.recommendation, "")
    analysis_lines = item.analysis.split("\n") if item.analysis else []
    content_parts = [f"{rec_label} 评分: {item.score}/10"]
    content_parts.extend(analysis_lines)
    elements.append({
        "tag": "markdown",
        "content": "\n".join(content_parts),
    })
    elements.append({"tag": "hr"})
    return elements


def build_feishu_card(digest: Digest) -> dict:
    elements = []
    elements.append({
        "tag": "markdown",
        "content": f"**📌 今日摘要**\n{digest.top_line}",
    })
    elements.append({"tag": "hr"})

    for section in digest.sections:
        if not section.items:
            continue
        elements.append({
            "tag": "markdown",
            "content": f"**{section.icon} {section.category}**",
        })
        for item in section.items:
            elements.extend(_item_to_feishu_elements(item))

    elements.append({"tag": "hr"})
    elements.append({
        "tag": "markdown",
        "content": "**🎯 今日推荐**",
    })
    if digest.must_read:
        for item in digest.must_read[:3]:
            elements.append({
                "tag": "markdown",
                "content": f"- [{item.title}]({item.url}) {REC_LABELS.get(item.recommendation, '')}",
            })
    else:
        elements.append({"tag": "markdown", "content": "- 今日无必读项"})

    if digest.monitor:
        elements.append({"tag": "markdown", "content": "**👁️ 待关注**"})
        for item in digest.monitor[:3]:
            elements.append({
                "tag": "markdown",
                "content": f"- [{item.title}]({item.url})",
            })

    return {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {
                    "tag": "plain_text",
                    "content": f"每日云原生速递 {digest.date}",
                },
                "template": "blue",
            },
            "elements": elements,
        },
    }


def _item_to_markdown(item: AnalyzedItem) -> str:
    rec_label = REC_LABELS.get(item.recommendation, "")
    lines = [
        f"### [{item.title}]({item.url})",
        f"**推荐**: {rec_label} | **评分**: {item.score}/10",
        "",
        item.analysis or "",
        "",
    ]
    return "\n".join(lines)


def build_markdown(digest: Digest) -> str:
    lines = [
        f"# 每日云原生速递 {digest.date}",
        "",
        f"> {digest.top_line}",
        "",
    ]

    for section in digest.sections:
        if not section.items:
            continue
        lines.append(f"## {section.icon} {section.category}")
        lines.append("")
        for item in section.items:
            lines.append(_item_to_markdown(item))

    lines.append("## 🎯 今日推荐")
    lines.append("")
    if digest.must_read:
        for i, item in enumerate(digest.must_read[:3], 1):
            lines.append(f"{i}. [{item.title}]({item.url})")
    else:
        lines.append("今日无必读项。")

    if digest.monitor:
        lines.append("")
        lines.append("## 👁️ 待关注")
        lines.append("")
        for item in digest.monitor[:3]:
            lines.append(f"- [{item.title}]({item.url})")

    if digest.optional:
        lines.append("")
        lines.append("## 📌 可忽略")
        lines.append("")
        for item in digest.optional[:3]:
            lines.append(f"- [{item.title}]({item.url})")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by Daily Cloud Native Briefing on {digest.date}*")
    return "\n".join(lines)
